stages:
  - test
  - build
  - publish

variables:
  DOCKER_IMAGE: private.nexus-registry.docker.local:8086/maven:3.9.5-eclipse-temurin-17-alpine
  DOCKER_VERSION: "stable"
  DOCKER_DIND_VERSION: "18.09-dind"
  DOCKER_CONFIG_FILE: "--config .docker"

test-unit:
  stage: test
  variables:
    POSTGRES_PASSWORD: mahasiswa
    POSTGRES_USER: mahasiswa
    POSTGRES_DB: mahasiswa
    DATABASE_HOST: postgres
  services:
    - name: private.nexus-registry.docker.local:8086/postgres:15.4
      alias: postgres
  image: $DOCKER_IMAGE
  script:
    - mvn clean test

build-jar:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - mvn clean -DskipTests package
  artifacts:
    paths:
      - target/*.jar
    name: build-jar

build-docker:
  stage: publish
  image: private.nexus-registry.docker.local:8086/docker:${DOCKER_VERSION}
  services:
    - name: private.nexus-registry.docker.local:8086/docker:${DOCKER_DIND_VERSION}
      entrypoint: [ "dockerd-entrypoint.sh" ]
      command: [
        "--insecure-registry=private.nexus-registry.docker.local:8087",
        "--insecure-registry=private.nexus-registry.docker.local:8086"
      ]
      alias: dockerd
  variables:
    DOCKER_HOST: tcp://dockerd:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILD_ARGS_ENTRIPOINT: "--build-arg JAR_FILE=mahasiswa-0.0.1-SNAPSHOT.jar"
    DOCKERFILE_LOCATION: "-f Dockerfile"
    DOCKER_TAGS:
      private.nexus-registry.docker.local:8087/uny/mahasiswa
    DOCKER_CONTEXT_PATH: "."
  before_script:
    - mkdir -p .docker/ && cat $DOCKER_CONF_JSON > .docker/config.json
  script:
    - docker build -q $DOCKERFILE_LOCATION $DOCKER_BUILD_ARGS_ENTRIPOINT -t private.nexus-registry.docker.local:8087/uny/mahasiswa:$CI_COMMIT_SHORT_SHA $DOCKER_CONTEXT_PATH
    - docker --config .docker image push private.nexus-registry.docker.local:8087/uny/mahasiswa:$CI_COMMIT_SHORT_SHA