stages:
    - test

variables:
    DOCKER_IMAGE: private.nexus-registry.docker.local:8086/maven:3.9.5-eclipse-temurin-17-alpine

build-jar:
    image: $DOCKER_IMAGE
    script: 
        - mvn clean -DskipTests package
    artifacts:
        paths:
            - target/*.jar
        name: build-jar