apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahasiswa-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mahasiswa-service
      tier: backend
      env: testing
      version: stable
  template:
    metadata:
      name: mahasiswa-service
      labels:
        app: mahasiswa-service
        tier: backend
        env: testing
        version: stable
    spec:
      containers:
        - name: mahasiswa-service
          image: 10.42.29.77:8086/uny/mahasiswa:24be5801