apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base

patches:
  - path: deployment.yaml
    target:
      name: mahasiswa-service
      kind: Deployment
      version: v1
      group: app